//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToysMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int Count { get; set; }
        public string FullName { get; set; }
        public string Telephone { get; set; }
        public string Address { get; set; }
        public int PaymentMethodId { get; set; }
        public int DeliverMethodId { get; set; }
        public int ProductId { get; set; }
    
        public virtual DeliverMethod DeliverMethod { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual Product Product { get; set; }
    }
}
